### ISSUE TITLE
I'm getting error "ERROR in Error: Error encountered resolving symbol values statically. Reference to a non-exported function (position 49:10 in the original .ts file), resolving symbol AppModule in"  while i'm working in Model-driven form or Reactive Form 

### ISSUE THREAD

**Issue by kveeresh49** [kveeresh49/angular-apppveeresh#1]
- I'm getting error "ERROR in Error: Error encountered resolving symbol values statically. Reference to a non-exported function (position 49:10 in the original .ts file), resolving symbol AppModule in"  while i'm working in Model-driven form or Reactive Form 

--ERROR in Error: Error encountered resolving symbol values statically. Reference to a non-exported function (position 49:10 in the original .ts file), resolving symbol AppModule in C:/Users/veereshbk/Desktop/angular-project-events/events-app/new-event-app/src/app/app.module.ts
    at positionalError (C:\Users\veereshbk\Desktop\angular-project-events\events-app\new-event-app\node_modules\@angular\compiler\bundles\compiler.umd.js:25134:35)
    at simplifyInContext (C:\Users\veereshbk\Desktop\angular-project-events\events-app\new-event-app\node_modules\@angular\compiler\bundles\compiler.umd.js:24977:27)
    at StaticReflector.simplify (C:\Users\veereshbk\Desktop\angular-project-events\events-app\new-event-app\node_modules\@angular\compiler\bundles\compiler.umd.js:24991:13)
    at StaticReflector.annotations (C:\Users\veereshbk\Desktop\angular-project-events\events-app\new-event-app\node_modules\@angular\compiler\bundles\compiler.umd.js:24418:41)
    at _getNgModuleMetadata (C:\Users\veereshbk\Desktop\angular-project-events\events-app\new-event-app\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (C:\Users\veereshbk\Desktop\angular-project-events\events-app\new-event-app\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (C:\Users\veereshbk\Desktop\angular-project-events\events-app\new-event-app\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (C:\Users\veereshbk\Desktop\angular-project-events\events-app\new-event-app\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (C:\Users\veereshbk\Desktop\angular-project-events\events-app\new-event-app\node_modules\@ngtools\webpack\src\plugin.js:212:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (C:\Users\veereshbk\Desktop\angular-project-events\events-app\new-event-app\node_modules\@ngtools\webpack\src\plugin.js:448:24)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[app.zip](https://github.com/kveeresh49/angular-apppveeresh/files/1716316/app.zip

)
@UltimateAngular/ngx-errors

**Comment by kveeresh49** [comment]
[1234.zip](https://github.com/kveeresh49/angular-apppveeresh/files/1727471/1234.zip)
[app.zip](https://github.com/kveeresh49/angular-apppveeresh/files/1727466/app.zip)

**Comment by kveeresh49** [comment]
veeresh

**Comment by kveeresh49** [comment]
[1234.zip](https://github.com/kveeresh49/angular-apppveeresh/files/1731455/1234.zip)  -- reactive Forms and Template Forms

**Comment by kveeresh49** [comment]
[src.zip](https://github.com/kveeresh49/angular-apppveeresh/files/2376392/src.zip)

**Comment by kveeresh49** [comment]
[package.zip](https://github.com/kveeresh49/angular-apppveeresh/files/2378063/package.zip)

**Comment by kveeresh49** [comment]
[src.zip](https://github.com/kveeresh49/angular-apppveeresh/files/2379621/src.zip)

**Comment by kveeresh49** [comment]
[src.zip](https://github.com/kveeresh49/angular-apppveeresh/files/2381595/src.zip)

**Comment by kveeresh49** [comment]
[src.zip](https://github.com/kveeresh49/angular-apppveeresh/files/2408402/src.zip)
